model:
  type: wresnet28_10
dataset: cifar100
aug: primaldual
randaug:
  N: 0
  M: 0    # from appendix
  weights: [0.0,1.0]
cutout: 16
batch: 128
n_aug: 7
gpus: 1
augmentation_search_space: wide_standard
epoch: 35
lr: 0.4
lr_schedule:
  type: 'cosine'
  warmup:
  multiplier: 1
  epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
MH:
  steps: 8
PD:
  lr: 0.0001
  margin: 0.9

