MH:
  steps: 2
PD:
  lr: 0.0001
  margin: 3.0
  sample: false
aug: primaldual
augmentation_search_space: wide_standard
batch: 128
cutout: 16
dataset: cifar100
epoch: 200
gpus: 1
lr: 0.1
lr_schedule:
  type: cosine
model:
  type: wresnet40_2
n_aug: 1
optimizer:
  decay: 0.0005
  nesterov: true
  type: sgd
randaug:
  M: 0
  N: 0
  weights:
  - 0.0
  - 1.0
save_model: true
seed: 1
