load_main_model: true
model:
  type: resnet50
dataset: imagenet
aug: primaldual
n_aug: 1
augmentation_search_space: wide_standard # they used 224 x 244
randaug:
  N: 0
  M: 0
  weights: [0.0,1.0]
cutout: 0
batch: 128
gpus: 1
epoch: 600
lr: .0005
lr_schedule:
  type: 'cosine' #'resnet'
#  warmup:
#    multiplier: 1.0
#    epoch: 3
optimizer:
  type: adam #sgd
#  nesterov: True # not in original
#  decay: 0.0001
#  clip: 0
seed: 0
MH:
  steps: 2
PD:
  lr: 0.0001
  margin: 0.7
  sample: False
frac_samples: 0.025

