model:
  type: wresnet40_2
dataset: cifar100
aug: primaldual
randaug:
  N: 1
  M: 20    # from appendix
  weights: [0.0,1.0]
cutout: 16
batch: 128
gpus: 1
n_aug: 1
augmentation_search_space: wide_standard
epoch: 200
lr: 0.1
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
MH:
  steps: 2
save_model: True
seed_set: 
        - 0
        - 1
        - 2
        - 3
        - 4
